---

name: Arch Linux PKGBUILD builder
description: Build an Arch Linux package
inputs:
  srcdir:
    description: "Path to directory containing PKGBUILD file"
    required: true
    default: ""
  outdir:
    description: relative output directory to store the built package
    required: false
    default: arch-packages
branding:
  color: blue
  icon: archive
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.srcdir }}"
    - "${{ inputs.outdir }}"