---

name: Arch Linux PKGBUILD builder
description: Build an Arch Linux package
inputs:
  pkgdir:
    description: "directory containing PKGBUILD file"
    required: true
    default: ""
branding:
  color: blue
  icon: archive
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.pkgdir }}"